name: Scout repository scan
on:
  workflow_dispatch: {}
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
permissions:
  contents: read
jobs:
  scout_repo_scan:
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Analyze for critical and high CVEs
        id: docker-scout-cves
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: docker/scout-action@bacf462e8d090c09660de30a6ccc718035f961e3 # v1
        continue-on-error: true
        with:
          command: cves
          image: fs://../${{ github.event.repository.name }}
          sarif-file: sarif.output.json
          summary: true
          ignore-base: true
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub-password: ${{ secrets.DOCKERHUB_RW_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # v4.36.0
        with:
          sarif_file: sarif.output.json
